<?php

namespace CompteUtilisateur\CompteUtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompteUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteUtilisateurRepository extends EntityRepository
{
    public function findUserMailbyRole($role)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('u.emailCanonical', 'u.roles')
            ->where('u.roles LIKE :roles')
    //        ->setParameter('roles', '%"ROLE_ADMIN"%');
            ->setParameter('roles', '%'.$role.'%');

        return $qb->getQuery()->getResult();
    }

    public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.taches like :chaine')
            ->orWhere('u.descriptionTache like :chaine')
            //->andWhere('u.actif = 1')
            ->orderBy('u.id')
            ->setParameter('chaine', '%'.$chaine.'%');
        return $qb->getQuery()->getResult();
    }

}
