newsletter:
    path:     /
    defaults: { _controller: "ExtranetBundle:Newsletter:index" }

newsletter_show:
    path:     /{id}/show
    defaults: { _controller: "ExtranetBundle:Newsletter:show" }

newsletter_new:
    path:     /new
    defaults: { _controller: "ExtranetBundle:Newsletter:new" }


newsletter_create:
    path:     /create
    defaults: { _controller: "ExtranetBundle:Newsletter:create" }
    methods:  POST


newsletter_delete:
    path:     /{id}/delete
    defaults: { _controller: "ExtranetBundle:Newsletter:delete" }
    methods:  [POST, DELETE]

newsletter_update:
    path:     /{id}/update
    defaults: { _controller: "ExtranetBundle:Newsletter:update" }
    methods:  [POST, PUT]

newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "ExtranetBundle:Newsletter:edit" }

newsletter_sendMail:
    path:     /{id}/show
    defaults: { _controller: "ExtranetBundle:Newsletter:send" }
    methods:  POST