<?php

namespace Extranet\ExtranetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetdocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetdocumentsRepository extends EntityRepository
{
}
