<?php

namespace Extranet\ExtranetBundle\Repository;

/**
 * ProjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsRepository extends \Doctrine\ORM\EntityRepository
{
    public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.nomProjet like :chaine')
            ->orWhere('u.descriptionProjet like :chaine')
            //->andWhere('u.actif = 1')
            ->orderBy('u.id')
            ->setParameter('chaine', '%'.$chaine.'%');
        return $qb->getQuery()->getResult();
    }


    public function updateDossier($dossier,$Id)
    {
        $qb = $this->createQueryBuilder('u');
        $q = $qb->update('ExtranetBundle:Projets','u')
            ->set('u.dossier', $qb->expr()->literal($dossier))
            ->where('u.id = ?1')
            ->setParameter(1, $Id)
            ->getQuery();
            $q->execute();
    }
}
