<?php

namespace Extranet\ExtranetBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheRepository extends \Doctrine\ORM\EntityRepository
{

    public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.Tache like :chaine')
            ->orWhere('u.DescriptionTache like :chaine')
            //->andWhere('u.actif = 1')
            ->orderBy('u.id')
            ->setParameter('chaine', '%'.$chaine.'%');
        return $qb->getQuery()->getResult();
    }
}
