Extranet\ExtranetBundle\Entity\Enquiry:
    type: entity
    table: null
    repositoryClass: Extranet\ExtranetBundle\Entity\EnquiryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        subject:
            type: string
            length: 255
        body:
            type: text
    lifecycleCallbacks: {  }
